spring:
  application:
    name: dubbo-springboot-demo-provider
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20889
  registry:
    address: nacos://10.10.1.90:8848?username=nacos&password=nacos&namespace=dubbojs4-ubuntu
#    address: zookeeper://127.0.0.1:2181
